#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# kill all child proceses
kill_spawn() {
  for SPAWN in $(pgrep -g $$); do
    kill $SPAWN
  done
}

# kill_spawn on exit and ctrl-c
trap kill_spawn EXIT SIGINT

# Define global variables and set defaults
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
RENDERED_FILENAME=periscope-$(date "+%y%m%d-%H%M").jpg
echo "starting generation of $RENDERED_FILENAME"
SCRAPE=1
DOWNLOAD=1
CROP=1
RENDER=1
DESKTOP=1
FLUSH=1
WX_WARN=1

# print out usage
usage() {
  cat <<EOF
USAGE: wd

Running wd without options will collect all assets,
render and set the desktop image to the output.

Individual options provided for debugging specific functions.

OPTIONS:
   -s    Scrape Sites
   -d    Download Images
   -c    Crop Images
   -r    Render Image
   -p    Set Desktop
   -f    Flush assets
   -h    Help
EOF
  exit 0
}

# process options and arguments
while getopts "hsdcrpf" OPTION; do
  case $OPTION in
  h) usage ;;
  s) SCRAPE=0 ;;
  d) DOWNLOAD=0 ;;
  c) CROP=0 ;;
  r) RENDER=0 ;;
  p) DESKTOP=0 ;;
  f) FLUSH=0 ;;
  esac
done

# ugly set the default action with no arguments are passed
if [[ $SCRAPE == 1 ]] && [[ $DOWNLOAD == 1 ]] && [[ $CROP == 1 ]] && [[ $RENDER == 1 ]] && [[ $DESKTOP == 1 ]] && [[ $FLUSH == 1 ]]; then
  SCRAPE=1 DOWNLOAD=0 CROP=1 RENDER=1 DESKTOP=0 FLUSH=0
fi

# path to this sripts repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
echo $SCRIPT_DIR

# flush assets
if [[ $FLUSH == 0 ]] && CLEANUP_FILES=$(compgen -G "${SCRIPT_DIR}/assets/periscope*.jpg"); then
  for CLEANUP_FILE in $CLEANUP_FILES; do
    echo "removing $CLEANUP_FILE"
    rm $CLEANUP_FILE
  done
fi

download() {
  set +e
  OUTPUT_FILE="$1"
  TARGET_URL="$2"
  # retry with counter
  RETRY_COUNTER=0
  until [ "$RETRY_COUNTER" -ge 5 ]; do
    echo "Downloading $OUTPUT_FILE"
    wget --quiet "$TARGET_URL" -O "$OUTPUT_FILE" && break
    sleep 5
    RETRY_COUNTER=$((RETRY_COUNTER + 1))
  done
}

# do the download
if [[ $DOWNLOAD == 0 ]]; then
  download "$SCRIPT_DIR/assets/$RENDERED_FILENAME" "http://periscope.jibb.tv/snap.jpeg" &
fi

# wait for asset collection to complete
if [[ $DOWNLOAD == 0 ]] || [[ $SCRAPE == 0 ]]; then
  wait
  echo "Asset Collection Completed..."
fi

# set the desktop pattern
if [[ $DESKTOP == 0 ]]; then
  if [[ -f "$SCRIPT_DIR/assets/$RENDERED_FILENAME" ]]; then
    echo "setting desktop to $SCRIPT_DIR/assets/$RENDERED_FILENAME"
    desktoppr 1 "$SCRIPT_DIR/assets/$RENDERED_FILENAME"
  else
    echo "Rendered file $SCRIPT_DIR/assets/$RENDERED_FILENAME not found..."
    echo "Run with render and set desktop at the same time"
  fi
fi

echo "End of Line..."
exit 0
